name: issue-event-workflow

on:
  issues:
    types: [opened]

jobs:
  issue-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: echo github action
    - name: |
      run : echo slack world
