name:workflow-dispatch
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'set name'
        required: true
        default: 'github-actions'
        type: string
      environment:
        description: 'set env'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1 echo hello world
        run: echo hello word!
      
      - name: step2 echo github action
        run: |
          echo hello word!
          echo github actions!
      
      - name: echo inputs
        run: |
          echo "NAME: ${{ inputs.name }}"
          echo "ENVIRONMENT: ${{ inputs.name }}"